sudo: false
language: ruby
cache: bundler
rvm:
  - 2.3.8
  - 2.4.7
  - 2.5.8
  - 2.6.6
  - 2.7.2
script:
  - bundle exec rake
gemfile:
  - gemfiles/faraday_0.15.gemfile
  - gemfiles/faraday_0.16.gemfile
  - gemfiles/faraday_0.17.gemfile
